0: 
      name : Simettric
      url : http://simettric.com
      logo_src: https://scontent-mad1-1.xx.fbcdn.net/v/t1.0-9/375641_240073739378993_1821969720_n.jpg?oh=3999b78ee4a1ece9833b1b71dbaf4e74&oe=59261568
1:
      name : Auzo Factory Matiko
      url : http://www.bilbao.eus/BilbaoEkintza/eu/index_eu.html
      logo_src: http://www.spri.eus/euskadinnova/uploads/images/noticias/innosocial/AuzoFactory.png